name: heli10830
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pytorch
  - torchvision
  - torchaudio
  - cudatoolkit=11.7
  - ca-certificates
  - openssl
  - numpy
  - scipy
  - opencv
  - tqdm
  - matplotlib
  - certifi
  - visdom
  - dominate
  - jupyterlab
  - notebook
  - conda-forge::pandas
